# Generated by Django 3.0.3 on 2020-05-03 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'judge_connection',
            },
        ),
        migrations.CreateModel(
            name='ParticipantConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_current_speaker', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'participant_connection',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_open', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('activated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('initial_connection_id', models.UUIDField(editable=False)),
                ('termination_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_pic_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('bio', models.CharField(blank=True, max_length=3000, null=True)),
                ('upvote_score', models.IntegerField(default=0)),
                ('email_is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ParticipantMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='', max_length=1000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('participant_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daseiner.ParticipantConnection')),
            ],
            options={
                'db_table': 'participant_message',
            },
        ),
        migrations.AddField(
            model_name='participantconnection',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daseiner.Room'),
        ),
        migrations.AddField(
            model_name='participantconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JudgeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='', max_length=1000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('judge_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daseiner.JudgeConnection')),
            ],
            options={
                'db_table': 'judge_message',
            },
        ),
        migrations.AddField(
            model_name='judgeconnection',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daseiner.Room'),
        ),
        migrations.AddField(
            model_name='judgeconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
