# Generated by Django 3.0.3 on 2020-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daseiner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmessage',
            name='body',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
