# Generated by Django 3.0.3 on 2020-05-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daseiner', '0002_auto_20200517_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmessage',
            name='body',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
