# Generated by Django 3.0.3 on 2020-05-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daseiner', '0004_auto_20200521_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='daseiner.Question'),
        ),
    ]
